### ISSUE TITLE
Typing svg has a new url

### ISSUE THREAD

**Issue by DenverCoder1** [simran2104/simran2104#1]
Hi,

I'm glad you are enjoying my typing svg animation code which you have on your profile!

I have now made it into a public repository and it has a new url.

The old link will be going away, so you will need to update your link to the new url.

Link to repo: https://github.com/DenverCoder1/readme-typing-svg

Thanks :smiley: 

(PS A :star2: on the repo would be nice :wink:)

**Comment by simran2104** [comment]
Okay, Thankyou for informing :)
